// <auto-generated />
using ASM_NET104.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASM.Migrations
{
    [DbContext(typeof(ASM_NET104Context))]
    [Migration("20210305140901_ASM_NET104New")]
    partial class ASM_NET104New
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASM_NET104.Models.ChiTietHd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("IdhoaDon")
                        .HasColumnName("IDHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaSp")
                        .HasColumnName("MaSP")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ChiTietHD");
                });

            modelBuilder.Entity("ASM_NET104.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("ASM_NET104Contenxt.Models.NhomSanPham", b =>
                {
                    b.Property<int>("MaNhom")
                        .HasColumnType("int");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.HasKey("MaNhom")
                        .HasName("PK__NHOM_San__234F91CD46FE5B5D");

                    b.ToTable("NHOM_SanPham");
                });

            modelBuilder.Entity("ASM_NET104Contenxt.Models.Sanpham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("MaSP")
                        .HasColumnType("INT")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("DonGia")
                        .HasColumnType("money");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("Nhom")
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasColumnName("TenSP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSp")
                        .HasName("PK__SANPHAM__2725081C4E59260D");

                    b.HasIndex("Nhom");

                    b.ToTable("SANPHAM");
                });

            modelBuilder.Entity("ASM_NET104Contenxt.Models.Sanpham", b =>
                {
                    b.HasOne("ASM_NET104Contenxt.Models.NhomSanPham", "NhomNavigation")
                        .WithMany("Sanpham")
                        .HasForeignKey("Nhom")
                        .HasConstraintName("FK__SANPHAM__Nhom__15502E78")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
